### ISSUE TITLE
Confusing naming in pyvespa: query.RankProfile and package.RankProfile

### ISSUE THREAD

**Issue by thigm85** [vespa-engine/pyvespa#12]
We have a class named `RankProfile` in the `vespa.package` module to create rank-profiles in the application package. However, we also have a class named `RankProfile` in the `vespa.query` module to define which rank-profile should be used in the query model.

This is unnecessarily confusing. I suggest we use `vespa.query.Ranking` instead of `vespa.query.RankProfile` to clarify the different use cases.

**Comment by kkraune** [comment]
We are adding _model_ as a new alias for rank profile, iirc - @bratseth is on this - so maybe we should use _model_ in this new API?

**Comment by thigm85** [comment]
Good point. However the issue remais as we would have `vespa.package.Model` to add a model into schema and `vespa.query.Model` to indicate which model to use when querying a Vespa instance. 

This is not really a big problem as the namespaces are different, it is just that it might be confusing for the user.

**Comment by thigm85** [comment]
Closing as it might not be an issue as originally thought.
