### ISSUE TITLE
Retrieving a running container with different VespaDocker instance will lead to deploy failure

### ISSUE THREAD

**Issue by thigm85** [vespa-engine/pyvespa#21]
It seems that previously defined volumes are not preserved. To reproduce try to deploy the same application with two different instances of VespaDocker. The first deployment will create the container. The second deployment will retrieve the already existing container but deployment will fail with

```
RuntimeError: ["Command failed. No directory or zip file found: '/app/application'", '']
```

**Comment by thomasht86** [comment]
No longer an issue.
