### ISSUE TITLE
Make it possible to specify the container image to use in the VespaDocker class

### ISSUE THREAD

**Issue by aressem** [vespa-engine/pyvespa#245]
In issue https://github.com/vespa-engine/pyvespa/issues/231 it would have been nice to specify the container image to use. This is not only for custom built or previews, but some users might also want to use the GitHub Docker Registry instead of Docker Hub (`ghcr.io/vespa-engine/vespa`) for container registry.

**Comment by thigm85** [comment]
@kkraune pyvespa 0.16.0 is out with the latest changes. 

Release instruction added on https://github.com/vespa-engine/pyvespa/pull/293, PTAL.

**Comment by kkraune** [comment]
VespaDocker now supports a container_image argument: https://pyvespa.readthedocs.io/en/latest/reference-api.html#vespadocker
