### ISSUE TITLE
Verbose pyvespa

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/pyvespa#297]
debugging pyvespa pipeline problems is easier in a verbose mode where responses from select operations are output to stdout (results from requests, etc).

Maybe an env var or something to enable

**Comment by thigm85** [comment]
Could you give a concrete example of the desired behavior?

**Comment by kkraune** [comment]
I am thinking about debug logging, that is default off, but can easily be enabled like 

````
        if os.getenv("PYVESPA_DEBUG") == "true":
            logging.basicConfig(level=logging.DEBUG)
````

so in the pyvespa code we can use

````
 logging.debug("Config Server check:" + output)
````

when debugging SD job failures, we can just add

````
export PYVESPA_DEBUG=true
````

and we get debug log not only from pyvespa code but other libraries. This has already helped me find one bug

**Comment by thigm85** [comment]
Make sense, `logging` is indeed missing from pyvespa.

**Comment by kkraune** [comment]
some files are now using debug logging since pyvespa 0.17.0, enable using by setting `PYVESPA_DEBUG=true` in the environment or `%env PYVESPA_DEBUG=true` in notebooks

https://github.com/vespa-engine/pyvespa/blob/master/vespa/deployment.py#L70
