### ISSUE TITLE
get_data and update_data are missing namespace

### ISSUE THREAD

**Issue by sephiartlist** [vespa-engine/pyvespa#317]
Hi
In the [document v1 api guide](https://docs.vespa.ai/en/document-v1-api-guide.html) the `put` (which  is used _under the hood_ inside the `batch_update`) has the separation between the `namespace` and the `schema`
e.g.
http://hostname:8080/document/v1/namespace/music/docid/1  
In [pyvespa the code](https://github.com/vespa-engine/pyvespa/blob/170a68db37f2369fff13cd80db6bba2a354bf256/vespa/application.py#L1424:1426)  for `get_data` and `update_data` does not separate between the `namespace` and the `schema`
e.g.
```
end_point = "{}/document/v1/{}/{}/docid/{}?create={}".format(
            self.app.end_point, schema, schema, str(data_id), str(create).lower()
)
```
This causes a bug while updating the documents with pyvespa (or doesn't update the document or creates a duplicate if the `create` parameter  is set to True

**Comment by thigm85** [comment]
Hi @sephiartlist, that is correct. The reason for that is that most applications have the same name for schema and document which often means that `http://hostname:8080/document/v1/music/music/docid/1` is the desired URL.

What is your use case, and how is the schema defined?

**Comment by sephiartlist** [comment]
Well  - In our case the deployment of the app was with a specific `namespace` which was different from the `schema`.

**Comment by sephiartlist** [comment]
I guess it is a wider issue it needs to be addressed also in 
1. delete_data
2. feed_data_point
3. delete_all_docs

**Comment by sephiartlist** [comment]
I've update the [application.py](https://github.com/vespa-engine/pyvespa/blob/master/vespa/application.py) file to handle `namespace`
All public methods have been added an optional argument `namespace`
I'm using it internally but It has not been tested .
Since I'm not sure about your development environment - i'll be happy to submit a PR - but if you prefer you can incorporate it  by yourself. 
See amended [application.py.txt](https://github.com/vespa-engine/pyvespa/files/8518555/application.py.txt)

**Comment by thigm85** [comment]
Hi @sephiartlist, I would be happy to review your PR if you want to create one. Let me know if you have questions about the development environment and any other issues that might block you.

**Comment by sephiartlist** [comment]
Hi @thigm85 ,
I'll try setting up the development environment - do you have any specific guidelines for contributions?
I'll be grateful if you can review my approach for solving this issue (see the above `application.py.txt` file), and direct me if you would like to take a different appoach

**Comment by thigm85** [comment]
Just submit a PR request with the code changes and we can discuss it in there.
