### ISSUE TITLE
Error when using onnx model on Windows

### ISSUE THREAD

**Issue by ingridsk** [vespa-engine/pyvespa#327]
Hi,

I have a problem when trying to deploy an app with an onnx model to Docker on Windows 10. 

When deploying the app on Docker, I get the following error:

```
vespa_docker = VespaDocker()
app = vespa_docker.deploy(application_package=app_package)
----------------------------------------------------------

RuntimeError: ["Uploading application '/app/application' using http://localhost:19071/application/v2/tenant/default/session", "Session 15 for tenant 'default' created.",
 'Preparing session 15 using http://localhost:19071/application/v2/tenant/default/session/15/prepared',
 'Request failed. HTTP status code: 400', 'Invalid application package: Error loading default.default: Could not parse schema file \'crossencoder.sd\':
 Unknown symbol: Lexical error at line -1, column 356.  Encountered: "\\\\" (92), after : ""', '']

```

The application package has worked on another OS, so the definition of it should not be the problem.

**Comment by lesters** [comment]
This error comes from within the Docker container. Is this related to the path of the ONNX model in the application package? How do you define the path to the ONNX model in PyVespa? Is the model in a subdirectory?

**Comment by kkraune** [comment]
Also let us know pyvespa version - we recently changed how you upload when deploying.

The latest pyvespa code is at https://github.com/vespa-engine/pyvespa/blob/master/vespa/package.py#L1391 , @lesters

**Comment by ingridsk** [comment]
The ONNX model is in the same directory as the notebook I am using, it is added to the application package through 

```
app_package.schema.add_model(
    OnnxModel(
        model_name="cross_encoder", 
        model_file_path="model.onnx", 
        inputs={
            "video_embedding": "attribute(video_embedding)", 
            "text_embedding": "query(text_embedding)"
        }, 
        outputs={"similarity": "similarity"}
    )
)

``` 

When I try to deploy the app, cross_encoder.onnx is added to crossencoder\application\files\cross_encoder.onnx. 
In the .sd file it is referenced in 


```
    onnx-model cross_encoder {
        file: files/cross_encoder.onnx
        input video_embedding: attribute(video_embedding)
        input text_embedding: query(text_embedding)
        output similarity: similarity
    }

```

I am on pyvespa 0.15.0, which I now see is not the newest version.

**Comment by kkraune** [comment]
Thanks! We are testing a possible error in https://github.com/vespa-engine/pyvespa/pull/328, I will update in an hour, and you can install from source to verify, I will let you know

**Comment by kkraune** [comment]
Just merged the fix, to be included in the next release. You can try it now by cloning https://github.com/vespa-engine/pyvespa, cd into `pyvespa` and run ` python3 -m pip install -e .[full]` - we are grateful if you can help use validate, we have poor windows testing for pyvespa. There might be other functions that fail on windows too ...

**Comment by ingridsk** [comment]
Hi,

Just letting you know that now I get the errors below. 



```
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

(...)

NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000203449BC9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

(...)

MaxRetryError: HTTPConnectionPool(host='localhost', port=19071): Max retries exceeded with url: /application/v2/tenant/default/prepareandactivate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000203449BC9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

(...)

ConnectionError: HTTPConnectionPool(host='localhost', port=19071): Max retries exceeded with url: /application/v2/tenant/default/prepareandactivate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000203449BC9D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

```

**Comment by kkraune** [comment]
thanks for reporting. can you check if there are active Docker containers (using the Docker console or command line) - and stop them before deploying again?

**Comment by thigm85** [comment]
I think this is still related to the path format expected by Windows. I will investigate why the fix proposed above is not working.

**Comment by thigm85** [comment]
The issue was not replicated and does not belong in the pyvespa score anymore.
