### ISSUE TITLE
pyvespa now makes it mandatory to include ml extra packages

### ISSUE THREAD

**Issue by lsena** [vespa-engine/pyvespa#341]
Hi!
While using the latest version, I'm now forced to install the ml dependencies when using Vespa/VespaAsync.

<img width="750" alt="image" src="https://user-images.githubusercontent.com/19229049/171396653-5e6e5db0-3c8f-4858-9d23-87dd09f09274.png">

**Comment by thigm85** [comment]
I will check that @lsena.

**Comment by thigm85** [comment]
@lsena please try again with pyvespa version 0.20.0.

**Comment by lsena** [comment]
Working as expected now, thanks!
