### ISSUE TITLE
Remove data plane certificate and key management from pyvespa

### ISSUE THREAD

**Issue by thigm85** [vespa-engine/pyvespa#343]
pyvespa currently generates a data plane certificate and key and stores it in a file every time a deployment is made. This behavior conflicts with the workflow of using the vespa-cli to generate API key and dataplane certificate and key.

I suggest we remove this functionality from pyvespa to rely solely on vespa-cli to set-up certificates and keys for Vespa Cloud interaction.

**Comment by thomasht86** [comment]
Closed by #809 
This is now done automatically by the `vespacli`-module
