### ISSUE TITLE
Adapt deploy to vespa cloud documentation notebook to run without errors in the CI pipeline

### ISSUE THREAD

**Issue by thigm85** [vespa-engine/pyvespa#344]
pyvespa [documentation page for Vespa Cloud deployment](https://pyvespa.readthedocs.io/en/latest/deploy-vespa-cloud.html) is currently not functional from an integration test point of view. Update [the notebook](https://github.com/vespa-engine/pyvespa/blob/master/docs/sphinx/source/deploy-vespa-cloud.ipynb) to make it functional. 

Take #343 into account as it simplified certificate and key management.

**Comment by thigm85** [comment]
@kkraune suggested looking into the possibility of using [vector-search](https://github.com/vespa-cloud/vector-search/pull/1#issuecomment-1144545487) app as the example in the deploy to cloud documentation.

**Comment by jobergum** [comment]
This integration https://github.com/vespa-engine/pyvespa/blob/master/vespa/test_integration_vespa_cloud_vector_search.py does exactly this. Resolving.
