### ISSUE TITLE
Support for document-summaries and struct datatypes

### ISSUE THREAD

**Issue by danclark382** [vespa-engine/pyvespa#362]
Is there a way to create a Struct data type within a schema? I have an array<struct> that I’m trying to use as an imported field, but I can’t find any reference for the struct field. 

Also is there any built-in support for creating document summaries?

**Comment by bratseth** [comment]
**Struct/array/importing**

Are you asking about struct, array, or importing either from parents?
- Structs: https://docs.vespa.ai/en/reference/schema-reference.html#struct
- Arrays: Under https://docs.vespa.ai/en/reference/schema-reference.html#field-types

You can import arrays from parent documents just like other field types. 
(You cannot refer to an array of parents, but I don't think you are asking about that.)

**Document summaries**

I assume you mean dynamic summary fields? Yes there is built-in support for that: https://docs.vespa.ai/en/reference/schema-reference.html#summary (see "dynamic").

You might also mean: Is it possible to select the fields to include in a summary, and have multiple such selections you can choose by query. For that, see https://docs.vespa.ai/en/reference/schema-reference.html#document-summary

**Comment by danclark382** [comment]
For both the struct and the summary, is there a way to implement these in Pyvespa? The links you sent are the correct items I'm mentioning. 

I'm trying to use Pyvespa to automate the configuration build of the Vespa application. If there isn't a way to create a struct in Pyvespa (like there is a Field within a schema), is there another automated process for building the configuration besides editing the files within the application directory?

Hope that clarifies the question a bit.

**Comment by bratseth** [comment]
Yes, that makes it clear. @thigm85 can answer best about Pyvespa, but it is *not* a design goal of it to be functionally complete for defining production applications, it only provides what's necessary for data science.

You need to have a source of truth which specifies what the schema and application package should contain.  I don't see why that should be in some other format than the native one provided by Vespa.

**Comment by danclark382** [comment]
That makes sense…thanks for the clarification!
