### ISSUE TITLE
Query with an embedding and field

### ISSUE THREAD

**Issue by TTitcombe** [vespa-engine/pyvespa#367]
I'm trying to run a query using nearest neighbour search while limiting it to records with a certain value, but I get errors when I try to combine the fields in a single yql query.

Using the example from [Image Search](https://pyvespa.readthedocs.io/en/latest/use_cases/image_search/image-search-scratch.html), I can run:
```python
response = app.query(body={
    "yql": 'select * from sources * where ([{"targetNumHits":100}]nearestNeighbor(embedding_image,embedding_text));',
    "hits": 100,
    "ranking.features.query(embedding_text)": [0.632, -0.987, ..., 0.534],
    "ranking.profile": "embedding_similarity"
})

```

and return results.
My records also have numerical attributes "value" and "cost". I can search to filter to a specific value of "value" or "cost" individually, or both of them together, e.g.
```
response = app.query(body={
    "yql": 'select * from sources * where (value=100 and cost=10);',
    "hits": 100
})
```

but when I try to combine the embedding search while filtering to a value, I get an error
```
response = app.query(body={
    "yql": 'select * from sources * where (value=100 and [{"targetNumHits":100}]nearestNeighbor(embedding_image,embedding_text));',
    "hits": 100,
    "ranking.features.query(embedding_text)": [0.632, -0.987, ..., 0.534],
    "ranking.profile": "embedding_similarity"
})
```

The error is 
```
mismatched input 'nearestNeighbor' expecting {<EOF>, 'select', ';'}
```

**Comment by thigm85** [comment]
Hi @TTitcombe, this should work. Do you have code and sample data so that I can try to reproduce and understand the error?

**Comment by TTitcombe** [comment]
I got it working by wrapping only the nearest neighbour search in brackets, i.e.
```
response = app.query(body={
    "yql": 'select * from sources * where value=100 and ([{"targetNumHits":100}]nearestNeighbor(embedding_image,embedding_text));',
    "hits": 100,
    "ranking.features.query(embedding_text)": [0.632, -0.987, ..., 0.534],
    "ranking.profile": "embedding_similarity"
})
```

I'll work on a minimal notebook example and share it

**Comment by jobergum** [comment]
Note that you don't need [] or to quote targetHit , many examples in https://docs.vespa.ai/en/nearest-neighbor-search-guide.html

```
select title, artist from track where {targetHits:10}nearestNeighbor(embedding,q)
```

**Comment by thigm85** [comment]
Great that you got it to work @TTitcombe.
