### ISSUE TITLE
Accessing deployed docker container from another IP?

### ISSUE THREAD

**Issue by TTitcombe** [vespa-engine/pyvespa#368]
I've deployed my Vespa app using pyvespa `VespaDocker`, which I can connect to on localhost on the same machine, but trying to connect to it from another machine results in a timeout. Do we need to run the application on 0.0.0.0 (as with flask, for example), to enable connection from external machines? If so, looking at the source code "localhost" is hardcoded in several places, so I guess it's not currently possible?

**Comment by thigm85** [comment]
Hi @TTitcombe, indeed `localhost` is currently hard-coded. We can change that. However, I am not sure if this alone would solve your problem. Have you tried this solution for a generic Docker application to see if using 0.0.0.0 works?

A quick look around seems that the solutions are more involved than that, e.g. [this article](https://blog.oddbit.com/post/2014-08-11-four-ways-to-connect-a-docker/).

**Comment by TTitcombe** [comment]
Thanks @thigm85. I think the issue I was experiencing was due to port access. Deploying on port 80 seemed to have resolved the issue (I'm a networking novice so I don't have an explanation for this). The context I left out was that this was being deployed on EC2, so I believe this is an AWS networking issue, not Vespa.

This raises another point about whether it's appropriate to try to deploy onto EC2 with PyVespa. Compared to the deployment instructions for plain Vespa, `vespa_docker.deploy` seems too simple. I don't want to derail this issue with other questions though - do you guys have a Slack or something similar to discuss this?

**Comment by thigm85** [comment]
We have a public Vespa Slack space ([vespatalk.slack.com](vespatalk.slack.com)). Feedback on how to improve `vespa_docker.deploy` is welcome :)

**Comment by kkraune** [comment]
We just added https://docs.vespa.ai/en/operations/multinode-systems.html#aws-singlenode this week for EC2 deployments, plmk if this helps or could be extended to improve pyvespa usage
