### ISSUE TITLE
Don't swallow query errors 

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/pyvespa#373]
As demonstrated in https://github.com/sha124/vespa/blob/main/VespaDocSimilarity.ipynb, if there is a parsing error in the query and the search result returns no hits + 4xx, the error is swallowed. The library should throw an error in this case.

**Comment by thigm85** [comment]
The error is currently not swallowed, `result.hits` returns an empty list, `result.status_code` returns 4xx and `result.json` returns the full Vespa response including the error message. This should be the desired behavior IMO since it represents what Vespa actually returns.

**Comment by johans1** [comment]
wontfix

**Comment by bratseth** [comment]
Maybe you could have a "troubleshooting" somewhere nearby that shows how to get more info.

**Comment by thigm85** [comment]
@bratseth, do you mean in the documentation?

**Comment by bratseth** [comment]
yes
