### ISSUE TITLE
Instructions on deploying to Vespa Cloud Prod

### ISSUE THREAD

**Issue by neo-anderson** [vespa-engine/pyvespa#395]
It seems like the process for deploying to Prod is different from dev deployments. Prod deployment page asks for 2 zip files. I downloaded the application zip file from Vespa Cloud, but I see that it's possible to do this with `to_files` call. However, I'm not sure how to generate the test package. Please help me understand the process.

**Comment by thigm85** [comment]
`pyvespa` allows only deployment to dev. `pyvespa` was built primarily to allow data scientists to experiment more quickly. It was not made for production use.

**Comment by neo-anderson** [comment]
Understood. What is the right way to convert the experiment into a production app? Currently, I have a sample app in dev that I'd like to deploy to prod. I generated the application package but prod deployment requires a test package as well. Do I have to manually create json files specifying the tests to run and then do `vespa prod submit` ?

**Comment by kkraune** [comment]
Hi, I'll get back to you shortly on this

**Comment by neo-anderson** [comment]
Thanks for looking into this. 
1. It's not just the console. `vespa prod submit` CLI command didn't work until I added a test package.
2. What would test files in a pyvespa project look like?
3. It would be great if you could include a simple test in the documentation to demonstrate the process. pyvespa generated or otherwise.

I am trying to find a work around. I'm not sure how to create a simple test to pass the checks and deploy the app to prod. Currently, I have this under `tests/system-tests`. 
```
{
    "name": "Very simple test",
    "comment": "Just want to deploy",
    "steps": [
        {
            "name": "query for foo",
            "request": {
                "parameters": {
                    "yql": "select * from sources * where True"
                }
            }
        }
    ]
}
```

**Comment by kkraune** [comment]
Hi, sorry for the trouble! I think there was a code change on Vespa Cloud today for this, I am not sure if it is fully rolled out yet - you can please let me know tomorrow if the CLI still fails after testing again then.

**Comment by kkraune** [comment]
@mpolden  does the vespa CLI require a test package for prod deployment?

**Comment by mpolden** [comment]
CLI itself shouldn't require a test package, but maybe the controller API does.

**Comment by neo-anderson** [comment]
Without the tests folder, this is what I get:
```
Warning: We recommend doing this only from a CD job
Hint: See https://cloud.vespa.ai/en/getting-to-production
Error: could not submit application for deployment: '' should be an application package zip or dir, but does not exist
```
After I added a .tests/system-test and a test file:
```
Warning: We recommend doing this only from a CD job
Hint: See https://cloud.vespa.ai/en/getting-to-production
Success: Submitted . for deployment
See https://console.vespa-cloud.com/tenant/dummycorp/application/myapp/prod/deployment for deployment progress
```

**Comment by mpolden** [comment]
I created https://github.com/vespa-engine/vespa/issues/24907 to track this issue.

**Comment by thomasht86** [comment]
This is now available (though still experimental.
https://pyvespa.readthedocs.io/en/latest/reference-api.html#vespa.deployment.VespaCloud.deploy_to_prod
