### ISSUE TITLE
Failed to run the Question Answering example

### ISSUE THREAD

**Issue by louisoutin** [vespa-engine/pyvespa#463]
Hello,

I tried to run the notebook located here: https://github.com/vespa-engine/pyvespa/blob/master/docs/sphinx/source/examples/semantic-retrieval-for-question-answering-applications.ipynb
Everything works fine until I reach the cell where it makes a query, I get an empty list as the result of the query (`result.hits = []`).
I'm running python 3.10 and made no modification to the notebook.
Any idea? Help would be appreciated. Thanks

PS: Thanks for this nice library.

**Comment by kkraune** [comment]
Thanks for reporting! I will see if I can reproduce and update here.

**Comment by louisoutin** [comment]
Forgot to mention i'm using latest version from pypi (pyvespa==0.31.0). Didn't try using master branch directly

**Comment by kkraune** [comment]
I was running this notebook earlier this week with no issues, so I suspect there is something with your environment. Often too little Docker memory is the culprit, you can review https://pyvespa.readthedocs.io/en/latest/troubleshooting.html. You will see in the Docker output if a process crashes. 

I will try again with a 4G setting but this notebook takes some time to run so probably update here tomorrow

**Comment by louisoutin** [comment]
Thanks for the quick help. What was strange is that I didn't got any error message on the notebook and no error on the docker logs also. I'll try with manually setting more ram to the docker container. Will update tomorrow.

**Comment by kkraune** [comment]
In step 18 I just got:
````

{'id': 'id:sentence:sentence::2',
 'relevance': 0.5540203635649571,
 'source': 'qa_content',
 'fields': {'sddocname': 'sentence',
  'documentid': 'id:sentence:sentence::2',
  'questions': [0],
  'dataset': 'squad',
  'context_id': 0,
  'text': 'It is a replica of the grotto at Lourdes, France where the Virgin Mary reputedly appeared to Saint Bernadette Soubirous in 1858.'}}
````

**Comment by kkraune** [comment]
I run pyvespa from head (checked out local version), and 3.10, too

**Comment by kkraune** [comment]
I added 
````
    @property
    def json(self):
        return self.json
````
to my local pyvespa install to be able to dump the full response object, I think we will add this to future releases

**Comment by kkraune** [comment]
https://github.com/vespa-engine/pyvespa/pull/465/files

**Comment by louisoutin** [comment]
Actually I just found the error. When feeding the data with `app.feed_data_point()`, I got a 'NO SPACE' error. Related to this: https://docs.vespa.ai/en/operations/feed-block.html. Will try to make space for docker and it should fix it.
Just as a note, maybe the notebook could be updated with a check for the returned code of `feed_data_point()` and throw an error with link to this feed-block page if NO SPACE error is found.

**Comment by kkraune** [comment]
Awesome!

Yes, totally agree on the error check - will look into - and also add to troubleshooting (this is a common problem), keeping this issue open until done

**Comment by kkraune** [comment]
https://github.com/vespa-engine/pyvespa/pull/466

**Comment by louisoutin** [comment]
Hey, when are you planning on releasing a new version of pyvespa? (0.32). Cause currently, on the 0.31, package.Field doesn't have the argument 'match'.
Thanks

**Comment by kkraune** [comment]
We hope to release it this sprint, meaning in a week or two
