### ISSUE TITLE
Question about content_cluster_name argument in delete_all_docs method

### ISSUE THREAD

**Issue by louisoutin** [vespa-engine/pyvespa#469]
Hello,
In the doc reference API, the class `classvespa.application.Vespa` has a method `delete_all_docs` with an argument called `content_cluster_name`. I'm not sure how to know what's my cluster name since when initializing the Application Package or when feeding the data, there is no such argument. I've checked the code and the vespa server doc, but I didn't find answers. Would be nice to have more information/examples about this `content_cluster_name` argument.
Thanks

**Comment by kkraune** [comment]
off the bat, I _think_ it is the same as the schema name, so you can try that. will update documentation regardless. thanks for reporting!

**Comment by louisoutin** [comment]
Will try that, thanks

**Comment by louisoutin** [comment]
Great! thanks!
