### ISSUE TITLE
Add field to schema

### ISSUE THREAD

**Issue by aamir-s18** [vespa-engine/pyvespa#497]
Hey, I noticed that in the [specs](https://docs.vespa.ai/en/reference/schema-reference.html#field), it is mentioned that it is possible to add a field to a schema. However, the current implementation adds the fields directly to the document of the schema. 

I wanted to run this [sample app](https://github.com/vespa-engine/sample-apps/tree/master/multi-vector-indexing) in Python. However, I encountered the following issue: "...'paragraph_embeddings': Indexing expression 'embed' attempts to modify the value of the document field 'paragraph_embeddings'. Use a field outside the document block instead."

It would be great if this support would be added.

Thank you!

**Comment by lesters** [comment]
Yes, pyvespa currently doesn't support adding fields directly under schema and not in the document. You would have to write the application package and schema yourself, and have pyvespa deploy that. I'll take a look at implementing this ASAP.

**Comment by lesters** [comment]
Fix: https://github.com/vespa-engine/pyvespa/pull/547
