### ISSUE TITLE
Allow to add configuration to content

### ISSUE THREAD

**Issue by medihack** [vespa-engine/pyvespa#520]
I would like to set up [`dynamic snippet configuration`](https://docs.vespa.ai/en/document-summaries.html#dynamic-snippet-configuration) using pyvespa. Unfortunately, it is not possible to add the `ApplicationConfiguration` to `content` (as noted in the documentation), because it is always rendered as a direct child of `services`, see [`services.xml` template](https://github.com/vespa-engine/pyvespa/blob/master/vespa/templates/services.xml).
Maybe an option `contentConfigurations` could be added to `ApplicationPackage` that accepts a list of `ApplicationConfiguration`. An alternative would be to recognize the configuration name and place the configuration to the correct location automatically.

**Comment by kkraune** [comment]
Do note that you can always use pyvespa to deploy from the application package files: https://pyvespa.readthedocs.io/en/latest/deploy-docker.html#Deploy-application-package-from-config-files - or just use the  https://docs.vespa.ai/en/vespa-cli.html
