### ISSUE TITLE
Types for RankProfile.inputs

### ISSUE THREAD

**Issue by kevinhu** [vespa-engine/pyvespa#544]
The types for the `inputs` of `RankProfile` in `vespa.package` are listed as `List[Tuple[str,str,str]]`:
https://github.com/vespa-engine/pyvespa/blob/3823564586b3f364f8ec43510f6029ce4738ff6b/vespa/package.py#L926-L936

Yet in the unit tests found in `vespa.test_package`, we see inputs of type `List[Tuple[str,str]]` being passed: https://github.com/vespa-engine/pyvespa/blob/3823564586b3f364f8ec43510f6029ce4738ff6b/vespa/test_package.py#L256-L272

Are both cases valid?

**Comment by lesters** [comment]
Yes, as per https://docs.vespa.ai/en/reference/schema-reference.html#inputs, inputs to rank profiles can have a third argument, which is a default value if not passed along with the query. But this is not tested in `vespa.test_package`.
