### ISSUE TITLE
Deprecation of PyVespa functionality

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/pyvespa#600]
In the upcoming pyvespa release, we are deprecating several APIs https://github.com/vespa-engine/pyvespa/pull/599 that will be removed in the release after. 

Using these will generate deprecation warnings.

- vespa.appplication.parse_feed_df
- vespa.application.df_to_vespafeed
- vespa.application.Vespa.query_batch
- vespa.application.Vespa.feed_batch
- vespa.application.Vespa.delete_batch
- vespa.application.Vespa.get_batch
- vespa.application.Vespa.update_batch
- vespa.application.Vespa.feed_df

The associated methods in `VespaSync` and `VespaAsync` are also deprecated.

**Comment by kkraune** [comment]
will be released in 0.8
