### ISSUE TITLE
clear explanation where does the docker container stores files

### ISSUE THREAD

**Issue by antonkulaga** [vespa-engine/pyvespa#672]
I need to index around 100GB of research articles with BAAI/bge-m3 in all modes. You provided a nice tutorial on how to configure multiple modes together, however I do not understand where exactly the data is stored in the docker container and where should I mount the volume to keep this data as adding 100GB of data will take multiple days and may be disrupted (so I have to be able to resume).

**Comment by kkraune** [comment]
Hi! https://docs.vespa.ai/en/operations-selfhosted/docker-containers.html#mounting-persistent-volumes is a good place to start. I think for your case it makes sense to set up the containers with the right settings yourself and connect to these from pyvespa
