### ISSUE TITLE
Type hint of RankProfile inputs

### ISSUE THREAD

**Issue by medihack** [vespa-engine/pyvespa#676]
In pyvespa (v0.38.0) the `inputs` attribute of `RankProfileFields` has a type hint of `inputs: List[Tuple[str, str, str]]`. But the [quickstart guide](https://pyvespa.readthedocs.io/en/latest/getting-started-pyvespa.html) only uses a tuple with two elements. What is the third element in the tuple? Or is it just wrongly typed?

**Comment by bratseth** [comment]
The (optional) default value. 

We should document this better.

**Comment by medihack** [comment]
If the third value is optional, wouldn't it then make sense to type hint it as `List[Tuple[str, str] | Tuple[str, str, str]]`?

**Comment by bratseth** [comment]
Yes, you are right - that too.
