### ISSUE TITLE
VespaAsync _open_aiohttp_session method doesn't need to be async

### ISSUE THREAD

**Issue by PrathamSoni** [vespa-engine/pyvespa#695]
Would remove some marginal asyncio overhead if the method was made synchronous. It can still be called in __aenter__ context with the same performance as the code is blocking anyways. 

Would be helpeful in terms of overall design patterns where similar long-running clients can all be started/managed together as such "start" methods are not async in nature (just creating some httpx/aiohttp client as is done here)

**Comment by thomasht86** [comment]
Closed by #849. Thanks @PrathamSoni 👍
