### ISSUE TITLE
pyvespa assumes vespaengine/vespa is pulled

### ISSUE THREAD

**Issue by kkraune** [vespa-engine/pyvespa#739]
when running feed_performance.ipynb I get
````
NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/create?name=pyvespafeed: Not Found ("no such image: docker.io/vespaengine/vespa: image not known")
````

````
$ docker images
REPOSITORY                TAG         IMAGE ID      CREATED      SIZE
docker.io/library/ubuntu  latest      7af9ba4f0a47  6 days ago   80.4 MB
docker.io/ollama/ollama   latest      00f930aadaff  12 days ago  431 MB
$ 
````

so the image is not there - it should be pulled in this case

**Comment by thomasht86** [comment]
I am not able to reproduce. Tried to delete and prune all images. 
The docs also say that it should pull if it not exists. 
https://github.com/vespa-engine/pyvespa/blob/90d5342eefe9368cf6527fa7a042630e49c179ab/vespa/deployment.py#L404C1-L404C56 
https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.run
https://docs.docker.com/reference/cli/docker/container/run/

Could I ask you try once more?

**Comment by kkraune** [comment]
I cannot reproduce either - must have been a misconfig somewhere in my podman/docker transitions
