### ISSUE TITLE
Make docker dependency optional

### ISSUE THREAD

**Issue by andreer** [vespa-engine/pyvespa#768]
Suggestion: make docker (and pontentially more) dependencies optional, in the case where pyvespa is only being used as a client library to an existing vespa setup.

**Comment by thomasht86** [comment]
Is it mostly to make the package lighter, or have you encountered any issues with regards to the docker dependency? 
If only the first, considering the small size of the `docker`-package: https://pypi.org/project/docker/7.0.0/#files, i think it would not justify much effort. 
If the latter, it would be easy to make a lightweight option (`pip install pyvespa[no-docker]`). 
Then we wouldn't need to change anything in CI etc.

**Comment by tokle** [comment]
Suggestion:  `pip install pyvespa[no-docker]`

**Comment by thomasht86** [comment]
Upon further investigation, I found that the suggestion contradicts the related [PEP](https://peps.python.org/pep-0735/#limitations-of-extras), and thus is not supported in `pyproject.toml` by default. 
I could still make it happen, by adding back a setup.py, but it doesn't feel like a good practice. 

Given the small size of the docker dependency (259kB), is it worth it? @andreer @jobergum

**Comment by jobergum** [comment]
no

**Comment by thomasht86** [comment]
Checked whether the `docker`-package introduced many other dependencies as well, but it does not. 

`pip show docker`

```python
Name: docker
Version: 7.0.0
Summary: A Python library for the Docker Engine API.
Home-page: https://github.com/docker/docker-py
Author: 
Author-email: 
License: Apache License 2.0
Location: /Users/thomas/.pyenv/versions/3.11.8/envs/pyvespa-build/lib/python3.11/site-packages
Requires: packaging, requests, urllib3
Required-by: pyvespa
```

Ok to close the issue?

**Comment by jobergum** [comment]
👍
