### ISSUE TITLE
Make it more obvious how to retrieve a reference to `Vespa` without redeploying

### ISSUE THREAD

**Issue by thomasht86** [vespa-engine/pyvespa#796]
Most of our examples show only how to get a reference to a `Vespa` app after deploying. 
For many cases, people want to create a reference to an existing app. 
This should be made more obvious, both in docs and with a section in the notebooks explaining this.

**Comment by YashasviMantha** [comment]
Agree! I propose a simple new cell with the relevant info in the notebooks [here](https://github.com/vespa-engine/pyvespa/tree/master/docs/sphinx/source). For example in this [notebook](https://github.com/vespa-engine/pyvespa/blob/master/docs/sphinx/source/getting-started-pyvespa.ipynb).

Obviously, happy to add them if you agree.

**Comment by thomasht86** [comment]
Added in 
- https://pyvespa.readthedocs.io/en/latest/getting-started-pyvespa-cloud.html
- https://pyvespa.readthedocs.io/en/latest/authenticating-to-vespa-cloud.html

And docstring: https://pyvespa.readthedocs.io/en/latest/reference-api.html#vespa
