### ISSUE TITLE
deploy_to_prod return value should be Vespa

### ISSUE THREAD

**Issue by marcosestevewhalar** [vespa-engine/pyvespa#800]
The return value for deploy_to_prod should be Vespa similar to deploy function 
```
    def deploy_to_prod(
        self,
        instance: Optional[str] = "default",
        disk_folder: Optional[str] = None,
        max_wait: int = 300,
    ) -> None:
```

**Comment by thomasht86** [comment]
Hi @marcosestevewhalar! 
A prod deployment may take a very long time in some cases, so this will probably not be desirable, and we want to match behavior of CLI, which prints/returns status endpoint. Maybe we can implement a check_status()-method, that could check if deployment has succeeded, similar to 
https://docs.vespa.ai/en/vespa-cli#deployment
