### ISSUE TITLE
Possible bug in VespaAsync/Vespa.asyncio

### ISSUE THREAD

**Issue by Kutsko** [vespa-engine/pyvespa#866]
I ran into an issue with the built-in async client. I'm using Vespa Cloud with pretty basic settings. 

```
vespa = VespaCloud(...)

client = vespa.get_application()

async_app = client.asyncio()

await async_app.query(yql = 'select * from schema where true')
```

This results in the error: 
```
AttributeError: 'NoneType' object has no attribute 'post'
```

Reading through the source code I figured out the following workaround: 

```
async_app = client.asyncio()
await async_app._open_aiohttp_session()
```

Once the session is non-None, the aysnc queries are awaitable as expected.

**Comment by thomasht86** [comment]
Hi! 
So the proper way to use the async client is as a context-manager. 

```
app: Vespa = vespa_cloud.get_application()
async with app.asyncio() as sess:
    response = await sess.query(yql = 'select * from doc where true')
response.json
```

You can see some more of the usage in [this notebook](https://pyvespa.readthedocs.io/en/latest/examples/feed_performance.html).

lmk if this works for you!

**Comment by thomasht86** [comment]
And I will create an issue to add example usage to the reference doc!

**Comment by Kutsko** [comment]
Ah, this solves my problem perfectly, thanks! Also appreciate the doc update.
