### ISSUE TITLE
Unable to access termios submodule on Windows

### ISSUE THREAD

**Issue by Kribra** [vespa-engine/pyvespa#869]
Hi, we recently upgraded pyvespa from 0.40 to 0.45. This then caused the following issue: "No module named 'termios'"
<img width="385" alt="image" src="https://github.com/user-attachments/assets/46a4cfce-139e-447e-9ba8-5512c321af64">

Quick google search shows that this is a Linux-based module, but we are chained to using Windows in our project. No issue with 0.40, so there seems to be an introduced error.

**Comment by thomasht86** [comment]
Thanks for reporting. 
This should be fixed in the coming release, due to https://github.com/vespa-engine/pyvespa/pull/845. 
Can recommend using WSL to use more features of pyvespa. 
Anyway, closing this.
