### ISSUE TITLE
Add compression support

### ISSUE THREAD

**Issue by jobergum** [vespa-engine/pyvespa#872]
Adding accept-encoding to the request will make Vespa compress the response, which can reduce latency for cross-region query traffic: 

```Accept-Encoding: gzip```

**Comment by thomasht86** [comment]
This is the default behavior for both `httpx` and `requests`. 
See
They will also be decompressed automatically.
See #883 
- From [httpx docs](https://www.python-httpx.org/quickstart/):
> Any gzip and deflate HTTP response encodings will automatically be decoded for you.
- From [requests FAQ](https://requests.readthedocs.io/en/latest/community/faq/):
> Requests automatically decompresses gzip-encoded responses, and does its best to decode response content to unicode when possible.
