### ISSUE TITLE
How to setup GPU configuration in Pyvespa?

### ISSUE THREAD

**Issue by laura-y7860** [vespa-engine/pyvespa#974]
I was wondering if there is any document available how to configure GPU in Pyvespa? 

Many Thanks,

**Comment by thomasht86** [comment]
Hi! 

If you are using [Vespa Cloud](cloud.vespa.ai), this is handled for you if you specify `gpu`-in services.xml (see https://cloud.vespa.ai/en/reference/services#gpu). 

If you are running local docker/podman, see [this](https://docs.vespa.ai/en/operations-selfhosted/vespa-gpu-container.html) guide for how to configure. 

Hope that helps,

**Comment by laura-y7860** [comment]
Thank you so much for your response,

I have manged to setpu GPU as the picture below: 
![image](https://github.com/user-attachments/assets/ef2bb669-c8a5-49db-aa7c-ae2fc041002d)

and ideally, I was hoping to make `app.feed_iterable` go faster with this setup but it doesn't seem to be utilising the configuration. Is there any other step I need to take to get this working?
![image](https://github.com/user-attachments/assets/226e16ea-83bb-4645-8e8d-f7c6cf2e2db2)


Thanks,

**Comment by thomasht86** [comment]
Hi, so I see you are able to install the driver, but must refer back to [this doc](https://docs.vespa.ai/en/operations-selfhosted/vespa-gpu-container.html) for making the vespa container detect and use the GPU. 
Unfortunately, this is different dependent on host configuration/hardware, so we are unable to provide exact instructions that will work for all. 
Also note that this is not pyvespa-specific. If you are able to to follow the steps in the link, pyvespa will also use GPU if configured to use the same docker image. 
Good luck, 
Thomas
